Name: Demo
Version: 0.1.0
Link: https://github.com/Webiny/Demo
Description: The Demo app is a showcase of different view types and components to be used as a starting point for creation of your own apps
Author:
    Name: Webiny LTD
    Email: info@webiny.com
    Link: https://www.webiny.com

Storage:
    Services:
        Demo:
            Class: \Webiny\Component\Storage\Storage
            Arguments:
                Driver:
                    Object: \Webiny\Component\Storage\Driver\Local\LocalStorageDriver
                    ObjectArguments:
                        Config:
                            Directory: __DIR__/../../public_html/uploads/demo
                            PublicUrl: __Webiny.WebUrl__/uploads/demo
                            Create: true