Name: Demo
Version: 0.1.0
Link: http://www.webiny.com/store/webiny/demo/
Description: The Demo app is a showcase of different view types and components to be used as a starting point for creation of your own apps

AuthorName: Webiny LTD
AuthorLink: http://www.webiny.com
AuthorEmail: info@webiny.com

Storage:
    Services:
        Demo:
            Class: \Webiny\Component\Storage\Storage
            Arguments:
                Driver:
                    Object: \Webiny\Component\Storage\Driver\Local\LocalStorageDriver
                    ObjectArguments:
                        - __DIR__/../../public_html/uploads/demo
                        - __Application.WebPath__/uploads/demo
                        - false
                        - true